In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [3]:
a.ndim


1

In [4]:
a.itemsize


4

In [5]:
a.dtype


dtype('int32')

In [6]:
b=np.array([[1,3.3],[4.6,3]])

In [7]:
b

array([[1. , 3.3],
       [4.6, 3. ]])

In [8]:
b.itemsize


8

In [9]:
a.size


5

In [10]:
a.shape


(5,)

In [11]:
b.shape


(2, 2)

In [14]:
c=np.zeros((3,4))

In [15]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
d=np.linspace(1,5,100)

In [17]:
d

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [18]:
d.ndim

1

In [19]:
d.reshape(10,10)

array([[1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
        1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636],
       [1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
        1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677],
       [1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
        2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717],
       [2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
        2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758],
       [2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
        2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798],
       [3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
        3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838],
       [3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
        3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879],
       [3.82828283, 3.86868687, 3.9090909

In [20]:
c.min()

0.0

In [21]:
d.max()

5.0

In [22]:
d


array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [23]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [24]:
a.sum()

15

In [25]:
b.sum()

11.899999999999999

In [26]:
b.sum(axis=0)

array([5.6, 6.3])

In [27]:
np.std(c)

0.0

In [28]:
e=np.rand((3,4))

AttributeError: module 'numpy' has no attribute 'rand'

In [29]:
np.std(d)

1.166305860514025

In [30]:
a.dot(a)

55

In [31]:
a*a

array([ 1,  4,  9, 16, 25])

In [32]:
a*b

ValueError: operands could not be broadcast together with shapes (5,) (2,2) 

Done

In [33]:
nums=range(5)
nums

range(0, 5)

In [34]:
list(nums)


[0, 1, 2, 3, 4]

In [35]:
nums[1:5]

range(1, 5)