In [1]:
num=[1,2,3,4,5]
squares=[x ** 2 for x in num]
print(squares)

[1, 4, 9, 16, 25]


In [3]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"
d

<class 'tuple'>
5
1


{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [4]:
def hello(name, loud=False):
    if loud:
        print('HELLO, ', name.upper())
    else:
        print('Hello, ' ,name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello,  Bob
HELLO,  FRED


In [5]:
int(A)

NameError: name 'A' is not defined

In [6]:
int("a")

ValueError: invalid literal for int() with base 10: 'a'

In [7]:
a=4
a.type()

AttributeError: 'int' object has no attribute 'type'

In [8]:
type(a)

int

In [13]:
import numpy as np
np.random.random((2,2))

array([[0.46511056, 0.86432654],
       [0.94871799, 0.25355644]])

In [19]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out c= a[[0,1],[1,2]]the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
c= a[[0,1],[1,2]]

In [15]:
print(b,c)

[[2 3]
 [6 7]] [2 7]


In [16]:
print(b)

[[2 3]
 [6 7]]


In [17]:
print(c)

[2 7]


In [26]:
c=a[0:2,[1,2]]

In [27]:
print(c)

[[2 3]
 [6 7]]


In [28]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [29]:
a[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
a[[[1,2]]]

C:\Users\DELL\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
a[[[1,2]]]

C:\Users\DELL\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [35]:
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(a[0, 0],a[1, 1], a[2, 0])  # Prints "[1 4 5]"

[1 4 5]
1 4 5


In [36]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [39]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [46]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
v*w

219
219


array([ 99, 120])

In [49]:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"
v.shape()

[1 2 3]
[1 2 3]


TypeError: 'tuple' object is not callable

In [53]:
v.shape

(3,)

In [52]:
v = np.array([1,2,3])
v.shape

(3,)

In [55]:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"
v.shape

[1 2 3]
[1 2 3]


(3,)

In [56]:
x=v.T

In [57]:
x

array([1, 2, 3])

In [58]:
x.shape

(3,)

In [59]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
b=a[:3]

In [64]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
x*b

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [66]:
x.dot(b)

array([30, 36, 42])

In [67]:
x.T.dot(b)

array([30, 36, 42])

In [68]:
np.multiply(x.T,b)

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [69]:
np.dot(x.T,b)

array([30, 36, 42])

In [71]:
c=x.reshape(3,1)

In [72]:
c

array([[1],
       [2],
       [3]])

In [73]:
c.dot(b)

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [74]:
c*b

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [75]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])